
export const USER_LOADING = "USER_LOADING";

export const USER_SET_SELECTED = "USER_SET_SELECTED";

export const USER_SET_FIND_USERS = "USER_SET_FIND_USERS";
export const USER_CLEAR_FIND_USERS = "USER_CLEAR_FIND_USERS";

export const USER_SET_FIND_REPOS = "USER_SET_FIND_REPOS";

export const USER_SET_ERROR = "USER_SET_ERROR";
export const USER_CLEAR_ERROR = "USER_CLEAR_ERROR";
